extends "res://tests/M8Runtime.gd"

func _ready():
	await boot()
	dismiss()
	configure(6)
	var gun = Utils.player.gun
	check(Utils.player.dash_part is CPUParticles2D and Utils.player.dash_part.amount == 50,"dash keeps authored density without GPU simulation")
	check(gun.particles_box is CPUParticles2D and gun.particles_end is CPUParticles2D,"beam has no first-use GPU simulation programs")
	check(gun.particles_box.amount == 50 and gun.particles_end.amount == 24,"beam retains both authored particle densities")
	check(is_equal_approx(gun.particles_box.lifetime,0.3) and is_equal_approx(gun.particles_end.lifetime,0.3),"particle lifetime is unchanged")
	check(not gun.cast.enabled,"beam has no redundant automatic ray query")
	var expected: Array = []
	seed(918)
	for i in 32: expected.append(randi())
	seed(918)
	var emitter = load("res://game/effects/LightweightParticles.gd").new()
	check(expected.find(randi()) == (1 if DisplayServer.get_name() == "headless" else 2),"converted emitter preserves baseline allocation RNG")
	emitter.free()
	seed(918)
	var model = Utils.weapon_list["6"].instantiate()
	check(expected.find(randi()) == (2 if DisplayServer.get_name() == "headless" else 4),"weapon creation preserves baseline gameplay RNG")
	model.free()
	seed(918)
	gun._shootAnim()
	check(expected.find(randi()) == (4 if DisplayServer.get_name() == "headless" else 6),"shoot animation preserves baseline gameplay RNG")
	var children = gun.get_child_count()
	for shot in 20: gun._shootAnim()
	check(gun.get_child_count() == children,"repeated shots reuse source flash without particle-node churn")
	gun.cancel_actions()
	var idle_points = gun.line_2d.points.duplicate()
	gun.global_position += Vector2(30,20)
	for tick_index in 60: gun._physics_process(1.0/60.0)
	check(gun.line_2d.points == idle_points,"idle beam leaves invisible geometry untouched")
	gun.openFire()
	gun._physics_process(1.0/60.0)
	check(gun.is_cast and gun.particles_box.emitting and gun.particles_end.emitting,"first shot immediately activates both emitters")
	gun.cancel_actions()
	check(not gun.is_cast and not gun.particles_box.emitting and not gun.particles_end.emitting and gun.line_2d.width == 0,"switch/reload cancellation clears beam and CPU emitters")
	await wait(0.6)
	check(not gun.is_cast and gun.line_2d.width == 0,"pending shot timeout cannot revive a cancelled beam")
	print("BEAM_PERFORMANCE checks=",checks," failures=",failures)
	if failures: get_tree().quit(1)
	else: await Demo.quit_game()
