extends "res://tests/M8Runtime.gd"

var callback_count := 0
var revived := false

func _ready():
	await boot()
	dismiss()
	var ui = Utils.canvasLayer
	var hud = ui.get_node("GameUI")
	check(hud.bottom_bls.get_children().all(func(child): return not child is Panel),"ammo readout leaves the battlefield visible")
	var boss_hud = preload("res://ui/BossHUD.gd").new()
	# Data-only observation: no test boss or damage mutation is needed for a UI trail.
	boss_hud.observe_health(1.0,11,0.0)
	boss_hud.observe_health(0.6,11,0.0)
	check(boss_hud.ratio == 0.6 and boss_hud.trailing_ratio == 1.0,"solid boss fill is immediate; only lost health trails")
	for step in 60: boss_hud.observe_health(0.6,11,1.0/60.0)
	check(is_equal_approx(boss_hud.trailing_ratio,0.6),"damage trail settles to real HP")
	boss_hud.observe_health(0.9,11,0.0)
	check(boss_hud.trailing_ratio == 0.9,"healing never leaves a false damage trail")
	boss_hud.observe_health(0.4,12,0.0)
	check(boss_hud.trailing_ratio == 0.4,"new boss resets the old damage trail")
	boss_hud.observe_health(1.0,13,0.0)
	for step in 60: boss_hud.observe_health(1.0-float(step+1)*0.005,13,1.0/60.0)
	check(boss_hud.trailing_ratio-boss_hud.ratio < 0.06,"sustained fire cannot keep a stale full-length trail")
	boss_hud.free()
	ui.showToast("first",0.01)
	await wait(0.07)
	ui.showToast("replacement",0.6)
	await wait(0.25)
	check(ui.toast_ui.visible and ui.toast.text == "replacement" and ui.toast_ui.modulate.a > 0.99,"replaced toast survives the previous fade callback")
	await wait(0.65)
	check(not ui.toast_ui.visible,"replacement toast still expires")
	var rewards = preload("res://ui/widgets/RewardChoose.tscn").instantiate()
	ui.add_child(rewards)
	await wait(0.05)
	check(rewards.list.get_child_count() == 3 and not rewards.info_label.text.is_empty(),"three rewards and initial description appear together")
	check(Demo.pause_stack.has(rewards),"reward panel retains pause ownership")
	for key in RewardServer.reward_list:
		var reward = RewardServer.reward_list[key].instantiate()
		rewards.onMouseIn(reward.reward_info)
		await wait(0.01)
		check(rewards.info_label.get_rect().end.y < rewards.get_node("NinePatchRect/Button").position.y,"reward description fits above actions "+str(key))
		reward.free()
	var old_choices = RewardServer.reward_shop_list.duplicate()
	rewards.loadList(false)
	check(rewards.list.get_child_count() == 3 and RewardServer.reward_shop_list == old_choices,"redraw does not reroll or stack reward cards")
	var gold_before = PlayerData.gold
	rewards._on_button_2_pressed()
	check(PlayerData.gold == gold_before-10 and rewards.list.get_child_count() == 3,"refresh retains its price and exactly three choices")
	var first = rewards.list.get_child(0)
	first.get_node("Button").grab_focus()
	await wait(0.01)
	check(rewards.info_label.text == tr(first.ins.reward_info),"keyboard focus reveals the same description as hover")
	for child in rewards.get_node("NinePatchRect").get_children():
		if child is Control:
			check(Rect2(Vector2.ZERO,rewards.get_node("NinePatchRect").size).encloses(child.get_rect()),"reward content stays on its surface "+child.name)
	rewards.queue_free()
	await wait(0.05)
	check(Demo.pause_stack.is_empty(),"closing rewards releases pause")
	var board = preload("res://ui/widgets/Scoreboard.tscn").instantiate()
	board.setData({"time":386,"kill":1240,"gold":7850,"stage":30})
	board.setCallBack(func(): callback_count += 1)
	ui.add_child(board)
	check(board.time.text == "06:26" and board.kill.text == "1240" and board.gold.text == "7850","result displays exact supplied totals")
	check(board.get_node("Panel/Route").text.contains("核心完成"),"route summary stays inside result panel")
	board._on_button_pressed()
	await wait(0.05)
	check(callback_count == 1 and Demo.pause_stack.is_empty(),"result confirmation calls back and releases pause")
	var death = preload("res://ui/widgets/DeathBoard.tscn").instantiate()
	death.setOnClick(func(value): callback_count += 1; revived = value)
	ui.add_child(death)
	gold_before = PlayerData.gold
	death._on_button_pressed()
	death._on_button_pressed()
	check(revived and callback_count == 2 and PlayerData.gold == gold_before-50,"revive retains exact cost and handles double activation once")
	await wait(0.05)
	print("FINAL_POLISH checks=",checks," failures=",failures)
	if failures: get_tree().quit(1)
	else: await Demo.quit_game()
